version: "3"

services:
  didikala_postgres:
    container_name: didikala_postgres
    image: postgres:14
    environment:
      - POSTGRES_DB=didikala
      - POSTGRES_USER=didikala
      - POSTGRES_PASSWORD=didikala
    volumes:
      - didikala_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  didikala_rabbitmq:
    container_name: didikala_rabbitmq
    image: rabbitmq:latest
    ports:
      - "5672:5672"
    restart: always


volumes:
  didikala_postgres_data:
    external: true
